PackageIdentifier: hoijunkim.shape
PackageVersion: 0.1.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: shape-gui.exe
    PortableCommandAlias: shape
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/hoijunkim/shape/releases/download/v0.1.1/shape-gui_v0.1.1_windows_amd64.zip
    InstallerSha256: A2291CFFACDE9B76BB1FE7BE344F90E342A46082EE355FB19311E97C5CD41E59
ManifestType: installer
ManifestVersion: 1.6.0
