// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['main']['App']['Cancel'](arg1);
}

export function CloseSource(arg1) {
  return window['go']['main']['App']['CloseSource'](arg1);
}

export function Codegen(arg1) {
  return window['go']['main']['App']['Codegen'](arg1);
}

export function ColumnStats(arg1) {
  return window['go']['main']['App']['ColumnStats'](arg1);
}

export function CountMatches(arg1) {
  return window['go']['main']['App']['CountMatches'](arg1);
}

export function DiffFiles(arg1, arg2) {
  return window['go']['main']['App']['DiffFiles'](arg1, arg2);
}

export function ExportQuery(arg1) {
  return window['go']['main']['App']['ExportQuery'](arg1);
}

export function GetCell(arg1) {
  return window['go']['main']['App']['GetCell'](arg1);
}

export function HelpSeen() {
  return window['go']['main']['App']['HelpSeen']();
}

export function LoadViews() {
  return window['go']['main']['App']['LoadViews']();
}

export function MarkHelpSeen() {
  return window['go']['main']['App']['MarkHelpSeen']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenSource(arg1) {
  return window['go']['main']['App']['OpenSource'](arg1);
}

export function ProfileFile(arg1) {
  return window['go']['main']['App']['ProfileFile'](arg1);
}

export function QueryRows(arg1) {
  return window['go']['main']['App']['QueryRows'](arg1);
}

export function SaveEdits(arg1) {
  return window['go']['main']['App']['SaveEdits'](arg1);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}

export function SaveText(arg1, arg2) {
  return window['go']['main']['App']['SaveText'](arg1, arg2);
}

export function SaveViews(arg1) {
  return window['go']['main']['App']['SaveViews'](arg1);
}

export function SchemaJSON(arg1) {
  return window['go']['main']['App']['SchemaJSON'](arg1);
}
